namespace GameStore.Api.Models;

/// <summary>
/// Represents a genre of games in the Game Store application. This class is used as an entity in the database to categorize games by their genre. Each genre has a unique identifier (Id) and a required name (Name). The Id property is typically generated by the database when a new genre is added, while the Name property must be provided when creating a new genre. This class is essential for organizing games within the application and allowing users to filter or search for games based on their genre.
/// </summary>
public class Genre
{
    /// <summary>
    /// Gets or sets the unique identifier for the genre. This property is typically generated by the database when a new genre is added. It serves as the primary key for the Genre entity in the database, allowing for efficient retrieval and management of genre records. The Id property is an integer and is essential for distinguishing between different genres in the application.
    /// </summary>
    public int Id { get; set; }
    
    /// <summary>
    /// Gets or sets the name of the genre. This property is required when creating a new genre and must be provided by the user. The Name property is a string that represents the name of the genre (e.g., "Fighting", "RPG", "Platformer"). It is used to categorize games within the application and allows users to filter or search for games based on their genre. The Name property is essential for providing meaningful information about the genre to users and for organizing games effectively within the Game Store application.
    /// </summary>
    public required string Name { get; set; }

}
